# Generated by Django 4.0.6 on 2022-07-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumbers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
